apiVersion: v1
kind: Service
metadata:
  labels:
    name: backend
  name: backend
spec:
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
      # we have to be sure that this port is not used by other nodes
      nodePort: 31111
  selector:
    app: backend
