apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
data:
  # this secret is base64 and can be decode here: https://www.base64decode.org/
  # its value is: mongodb://admin:password@mongodb:27017/guestbook?authSource=admin
  mongodb-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGI6MjcwMTcvZ3Vlc3Rib29rP2F1dGhTb3VyY2U9YWRtaW4=