apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  guestbook-name: "MyPopRock Festival 2.0"
  # it is address of node port used by the backend service, web browser will send requests to this address
  backend-uri: "http://localhost:31111/guestbook"
